site_name: SmartBrains Wiki
site_description: SmartBrains Documentation Website
repo_url: https://github.com/smartbrainsio/smartbrains-wiki
google_analytics: ['G-NQY603SV5K', 'wiki.smartbrains.io']
theme:
    name: 'material'
    logo: images/wikilogo.jpg
    favicon: 'images/favicon.ico'
    extra_css: 
      - stylesheets/extra.css
    palette:
      - primary: black
      - accent: red
nav:
    - Home: 'index.md'
    - Accelerators: 
        Analytics: 'analytics.md'
        Architecture: 'arch.md'
        Cloud: 'cloud.md'
        Development: 'dev.md'
        DevOps: 'devops.md'
        SecOps: 'secops.md'
    - About:
        FAQs: 'faq.md'
markdown_extensions:
    - attr_list
    - smarty
    - toc:
        permalink: True
    - sane_lists
